package io.github.hakjuoh.protege_mcp.tools;

import java.io.File;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.LocalDate;
import java.time.ZoneOffset;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;

import io.github.hakjuoh.protege_mcp.policy.ProjectInteroperability;
import io.github.hakjuoh.protege_mcp.policy.ProjectPolicyLoader;

/** Renders a policy starter and its matching minimal RO-Crate from live project coordinates. */
final class ProjectPolicyScaffold {

    static final String RO_CRATE_METADATA = "ro-crate-metadata.json";
    private static final ObjectMapper JSON = new ObjectMapper()
            .enable(SerializationFeature.INDENT_OUTPUT);

    private ProjectPolicyScaffold() {
    }

    static Scaffold prepare(Path target, Path documentPath, String ontologyIri,
            List<String> installedReasoners, String selectedReasoner, String profile,
            String configuredProjectId, int version) {
        if (documentPath == null || !Files.isRegularFile(documentPath)) {
            throw new ToolArgException("The active ontology must be saved to a regular local file "
                    + "before a valid project policy can be generated.");
        }
        if (ontologyIri == null) {
            throw new ToolArgException("The active ontology must have an ontology IRI before a "
                    + "valid project policy can be generated.");
        }
        String projectId = configuredProjectId != null && !configuredProjectId.isBlank()
                ? configuredProjectId.trim()
                : ProjectPolicyTemplate.deriveProjectId(ontologyIri);
        Path canonicalTarget = DirectAccessPolicy.canonicalCandidate(
                target.toAbsolutePath().normalize());
        Path projectRoot = ProjectPolicyLoader.canonicalProjectAnchor(canonicalTarget);
        Path document = DirectAccessPolicy.canonicalCandidate(documentPath);
        if (!document.startsWith(projectRoot)) {
            throw new ToolArgException("The active ontology document is outside the selected "
                    + "policy's project root: " + document);
        }
        String rootArtifact = portableRelative(projectRoot.relativize(document));
        String reasoner = reasoner(installedReasoners, selectedReasoner);
        ProjectPolicyTemplate.Template template = ProjectPolicyTemplate.render(profile, projectId,
                ontologyIri, version, rootArtifact, reasoner);
        byte[] policyBytes = template.yaml().getBytes(StandardCharsets.UTF_8);
        byte[] metadataBytes = metadata(projectId, rootArtifact, ontologyIri);
        return new Scaffold(projectRoot, projectId, profile, version, rootArtifact, template,
                policyBytes, projectRoot.resolve(RO_CRATE_METADATA), metadataBytes);
    }

    private static String reasoner(List<String> installed, String selected) {
        if (installed == null || installed.isEmpty()) return null;
        if (selected != null && !"none".equalsIgnoreCase(selected.trim())
                && installed.stream().filter(selected::equals).count() == 1) {
            return selected;
        }
        for (String candidate : installed) {
            if (candidate != null && candidate.toLowerCase(Locale.ROOT).contains("hermit")
                    && installed.stream().filter(candidate::equals).count() == 1) {
                return candidate;
            }
        }
        return installed.size() == 1 ? installed.get(0) : null;
    }

    private static byte[] metadata(String projectId, String rootArtifact, String ontologyIri) {
        Map<String, Object> descriptor = entity(RO_CRATE_METADATA, "CreativeWork");
        descriptor.put("about", ref("./"));
        descriptor.put("conformsTo", ref("https://w3id.org/ro/crate/1.1"));

        Map<String, Object> root = entity("./", "Dataset");
        root.put("name", projectId + " ontology project");
        root.put("description", "Ontology project scaffold generated by Protégé MCP.");
        root.put("datePublished", LocalDate.now(ZoneOffset.UTC).toString());
        root.put("license", "License not specified");
        root.put("identifier", projectId);
        root.put("conformsTo", ref(ProjectInteroperability.PROFILE_IRI));
        root.put("mainEntity", ref(rootArtifact));
        root.put("hasPart", ref(rootArtifact));

        Map<String, Object> profile = entity(ProjectInteroperability.PROFILE_IRI, "CreativeWork");
        profile.put("name", "Protégé MCP ontology project profile");

        Map<String, Object> artifact = entity(rootArtifact, "File");
        artifact.put("encodingFormat", mediaType(rootArtifact));
        artifact.put("about", ref(ontologyIri));

        Map<String, Object> ontology = entity(ontologyIri, "Dataset");
        ontology.put("conformsTo", ref(ProjectInteroperability.OWL2_SPEC));

        Map<String, Object> crate = new LinkedHashMap<>();
        crate.put("@context", "https://w3id.org/ro/crate/1.1/context");
        crate.put("@graph", List.of(descriptor, root, profile, artifact, ontology));
        try {
            return (JSON.writeValueAsString(crate) + "\n").getBytes(StandardCharsets.UTF_8);
        } catch (JsonProcessingException e) {
            throw new IllegalStateException("Could not render RO-Crate metadata", e);
        }
    }

    private static Map<String, Object> entity(String id, Object type) {
        Map<String, Object> entity = new LinkedHashMap<>();
        entity.put("@id", id);
        entity.put("@type", type);
        return entity;
    }

    private static Map<String, Object> ref(String id) {
        return Map.of("@id", id);
    }

    private static String mediaType(String path) {
        String lower = path.toLowerCase(Locale.ROOT);
        if (lower.endsWith(".ttl")) return "text/turtle";
        if (lower.endsWith(".json") || lower.endsWith(".jsonld")) return "application/ld+json";
        if (lower.endsWith(".obo")) return "text/obo";
        return "application/rdf+xml";
    }

    private static String portableRelative(Path relative) {
        return relative.toString().replace(File.separatorChar, '/');
    }

    record Scaffold(Path projectRoot, String projectId, String profile, int version,
            String rootArtifact, ProjectPolicyTemplate.Template template, byte[] policyBytes,
            Path metadataPath, byte[] metadataBytes) {
    }
}
